import type { SalesCashierTableRow } from '../types/sales-cashier-table.types';

export const mockData: SalesCashierTableRow[] = [
  {
    periode: '21/01/2025',
    nama_kasir: 'Kenneth Percy Allen',
    transaksi: '255 Transaksi',
    omzet: 'Rp 3.680.952',
    shift: '2 Shift',
    rata_rata_transaksi_per_shift: '127,5 Transaksi',
    transaksi_dibatalkan: '15 Transaksi',
    transaksi_retur: '6 Transaksi',
  },
  {
    periode: '20/01/2025',
    nama_kasir: 'Judith Ruth Rodriguez',
    transaksi: '252 Transaksi',
    omzet: 'Rp 3.680.952',
    shift: '2 Shift',
    rata_rata_transaksi_per_shift: '126 Transaksi',
    transaksi_dibatalkan: '2 Transaksi',
    transaksi_retur: '16 Transaksi',
  },
  {
    periode: '19/01/2025',
    nama_kasir: 'Paula Eve Mora',
    transaksi: '250 Transaksi',
    omzet: 'Rp 3.680.952',
    shift: '2 Shift',
    rata_rata_transaksi_per_shift: '125 Transaksi',
    transaksi_dibatalkan: '0 Transaksi',
    transaksi_retur: '17 Transaksi',
  },
  {
    periode: '18/01/2025',
    nama_kasir: 'Dennis Sebastian Callis',
    transaksi: '252 Transaksi',
    omzet: 'Rp 3.680.952',
    shift: '2 Shift',
    rata_rata_transaksi_per_shift: '126 Transaksi',
    transaksi_dibatalkan: '1 Transaksi',
    transaksi_retur: '11 Transaksi',
  },
  {
    periode: '17/01/2025',
    nama_kasir: 'Joshua Levi Jones',
    transaksi: '123 Transaksi',
    omzet: 'Rp 3.680.952',
    shift: '2 Shift',
    rata_rata_transaksi_per_shift: '61,5 Transaksi',
    transaksi_dibatalkan: '6 Transaksi',
    transaksi_retur: '3 Transaksi',
  },
  {
    periode: '16/01/2025',
    nama_kasir: 'John Ethan Dukes',
    transaksi: '116 Transaksi',
    omzet: 'Rp 3.680.952',
    shift: '2 Shift',
    rata_rata_transaksi_per_shift: '58 Transaksi',
    transaksi_dibatalkan: '2 Transaksi',
    transaksi_retur: '0 Transaksi',
  },
  {
    periode: '15/01/2025',
    nama_kasir: 'Stephanie Taya Sharkey',
    transaksi: '65 Transaksi',
    omzet: 'Rp 3.680.952',
    shift: '2 Shift',
    rata_rata_transaksi_per_shift: '32,5 Transaksi',
    transaksi_dibatalkan: '1 Transaksi',
    transaksi_retur: '1 Transaksi',
  },
];
